[package]
edition = "2021"
name = "command"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
morscrypta = {path = "..", version = "0.1.0"}
rand_core = "0.5.1"
regex = "1.3.5"
x25519-dalek = "0.6.0"
